# Generated by Django 3.2 on 2022-04-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joininfluencer',
            name='email_address',
            field=models.EmailField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='joininfluencer',
            name='full_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='joininfluencer',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
    ]
