# Generated by Django 3.2 on 2022-04-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220406_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='joininfluencer',
            name='description_influencer',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='joininfluencer',
            name='gender_influencer',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='joininfluencer',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='joininfluencer',
            name='title_influencer',
            field=models.CharField(default='', max_length=80),
        ),
    ]
