# Generated by Django 3.2 on 2022-04-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220406_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='joininfluencer',
            name='youtube_followers',
            field=models.CharField(default='', max_length=10),
        ),
    ]
