# Generated by Django 3.2 on 2022-04-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_joininfluencer_youtube_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='joininfluencer',
            name='twitch_followers',
            field=models.CharField(default='', max_length=20),
        ),
    ]
