# Generated by Django 3.2 on 2022-04-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_joininfluencer_twitch_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joininfluencer',
            name='instagram_followers',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='joininfluencer',
            name='instagram_username',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='joininfluencer',
            name='tiktok_followers',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='joininfluencer',
            name='tiktok_username',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='joininfluencer',
            name='twitch_followers',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='joininfluencer',
            name='twitch_username',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='joininfluencer',
            name='twitter_followers',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='joininfluencer',
            name='twitter_username',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='joininfluencer',
            name='website',
            field=models.URLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='joininfluencer',
            name='youtube_followers',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='joininfluencer',
            name='youtube_url',
            field=models.URLField(default='', null=True),
        ),
    ]
