# Generated by Django 3.2 on 2022-04-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20220407_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joininfluencer',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='joininfluencer',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='joininfluencer',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='joininfluencer',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='joininfluencer',
            name='instagram_followers',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='joininfluencer',
            name='instagram_username',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='joininfluencer',
            name='tiktok_followers',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='joininfluencer',
            name='tiktok_username',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='joininfluencer',
            name='twitch_followers',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='joininfluencer',
            name='twitch_username',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='joininfluencer',
            name='twitter_followers',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='joininfluencer',
            name='twitter_username',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='joininfluencer',
            name='website',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='joininfluencer',
            name='youtube_followers',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='joininfluencer',
            name='youtube_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
