# Generated by Django 3.2 on 2022-04-07 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20220407_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_platform', models.CharField(default='', max_length=100)),
                ('content_category', models.CharField(default='', max_length=50)),
                ('package_offering', models.CharField(default='', max_length=500)),
                ('package_include', models.CharField(default='', max_length=1000)),
                ('package_price', models.IntegerField(default=0)),
                ('influencer_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.joininfluencer')),
            ],
        ),
    ]
