# Generated by Django 3.2 on 2022-04-07 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_influencerpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerFaqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_question', models.CharField(max_length=500)),
                ('faq_answer', models.CharField(max_length=700)),
                ('influencer_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.joininfluencer')),
            ],
        ),
    ]
