# Generated by Django 3.2 on 2022-04-07 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_influencerfaqs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InfluencerFaqs',
            new_name='InfluencerFaq',
        ),
    ]
