# Generated by Django 3.2 on 2022-04-08 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20220408_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerfaq',
            name='influencer_username2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.joininfluencer'),
        ),
        migrations.AlterField(
            model_name='influencerpackage',
            name='influencer_username1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.joininfluencer'),
        ),
    ]
