# Generated by Django 3.2 on 2022-04-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20220408_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='influencerfaq',
            old_name='influencer_username2',
            new_name='influencer_username',
        ),
        migrations.RenameField(
            model_name='influencerpackage',
            old_name='influencer_username1',
            new_name='influencer_username',
        ),
        migrations.AlterField(
            model_name='joininfluencer',
            name='influencer_username',
            field=models.CharField(max_length=200),
        ),
    ]
