# Generated by Django 3.2 on 2022-04-12 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20220408_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditPortfolioImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, default='', max_length=300, null=True)),
                ('influencer_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.joininfluencer')),
            ],
        ),
    ]
